-- CreateEnum
CREATE TYPE "RepoStatus" AS ENUM ('PENDING', 'VALIDATING', 'REJECTED', 'PROCESSING', 'READY', 'FAILED');

-- CreateEnum
CREATE TYPE "JobStatus" AS ENUM ('QUEUED', 'RUNNING', 'COMPLETED', 'FAILED');
